[platformio]
default_envs=pocketwroom

[env:pocketwroom]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_upload.use_1200bps_touch = true

build_flags =
  -D PIN_TOUCH_LEFT=4
  -D PIN_TOUCH_RIGHT=5
  -D PIN_ROT_DT=14
  -D PIN_ROT_CLK=13
  -D PIN_ROT_BTN=12
  -D PIN_PADDLE_LEFT=2
  -D PIN_PADDLE_RIGHT=1
  -D PIN_KEYER=41
  -D PIN_BUTTON=0
  -D CONFIG_SOUND_I2S=1
  -D CONFIG_DECODER_I2S=1
  -D CONFIG_I2S_BCK_PIN=16
  -D CONFIG_I2S_LRCK_PIN=17
  -D CONFIG_I2S_DATA_PIN=18
  -D CONFIG_I2S_DATA_IN_PIN=8
  -D CONFIG_TLV320AIC3100=1
  -D CONFIG_TLV320AIC3100_SDA=15
  -D CONFIG_TLV320AIC3100_SCL=7
  -D CONFIG_TLV320AIC3100_INT=6
  -D CONFIG_TLV320AIC3100_RST=45
  -D PIN_VEXT=42
  -D VEXT_ON_VALUE=HIGH
  -D ST7789_DRIVER=1
  -D TFT_WIDTH=170
  -D TFT_HEIGHT=320
  -D TFT_MISO=-1
  -D TFT_MOSI=48
  -D TFT_SCLK=38
  -D TFT_CS=39
  -D TFT_DC=47
  -D TFT_RST=40
  -D TFT_BL=21
  -D TFT_OFFSET_X=35 ; T190 & CYD 1.9
  -D CONFIG_MCP73871=1
  -D CONFIG_MCP_PG_PIN=11
  -D CONFIG_MCP_STAT1_PIN=9
  -D CONFIG_MCP_STAT2_PIN=10
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D LV_CONF_INCLUDE_SIMPLE
 	-Iinclude



lib_deps =
  jsc/ArduinoLog@^1.2.1
  bblanchon/ArduinoJson@6.20.1
  madhephaestus/ESP32Encoder @ ^0.11.7
  https://github.com/haklein/cw-i2s-sidetone.git#v1.0.2
  haklein/tlv320aic31xx@^1.0.5
  https://github.com/haklein/DisplayWrapper.git
  WiFiClientSecure
  lovyan03/LovyanGFX
  jgromes/RadioLib@^7.1.0
  lvgl/lvgl

